### PR TITLE
Meet silly

### PR DESCRIPTION
**Pull request by AljoschaMeyer**

### CODE REVIEW

**Comment by AljoschaMeyer** [comment]
The sample rate of 44100hz does not appear to match that of `out`. Or at least that's the only explanation I can come up with for why generating waves at 440hz sounds roughly a whole tone higher than my trusty tuning fork.

**Comment by sandreae** [comment]
Hmm... I suppose we need to account for devices set to different sample rates if we want exact pitches...

I'd also thought about adding this module (love the name btw), but hesitated as when thinking about this whole repo as an instrument/performance tool, I like the fact that a lot of the (sound) character will come from the source audio (samples) chosen by the performer. I wonder once we introduce sound synthesis in this very powerful way, if it changes the character.... I'm not sure though, I also want to just make a sin tones sometimes.... Did you have use cases in mind for this?

**Comment by sandreae** [comment]
> The sample rate of 44100hz does not appear to match that of `out`. Or at least that's the only explanation I can come up with for why generating waves at 440hz sounds roughly a whole tone higher than my trusty tuning fork.

`out` now prints the device settings so you can check yours.

**Comment by AljoschaMeyer** [comment]
> Did you have use cases in mind for this?

I don't have a use case in mind for *anything* I have contributed to this repo! `silly` is mostly an excuse to use the name, and a pre-study for `pointy`, a gui input module that's essentially a virtual theremin. For which I don't have a use case either beyond "this is pretty cool and fun to implement".

**Comment by sandreae** [comment]
> I don't have a use case in mind for anything I have contributed to this repo! 

Haha sounds appropriate ;-p what I was asking came out wrong, what I meant was, tone generators are _dangerous_ if deployed boringly :rofl: which is easily done... the theremin sounds awesome though, let's live dangerously.

**Pull request merged**
