### PR TITLE
Meet imaginary

### PR DESCRIPTION
**Pull request by meike-h**
Creates a dual visualisation of the input audio file.
How does it work? -- Use your imagination.

### CODE REVIEW

**Comment by sandreae** [comment]
Hi! Thanks for this PR @meike-h, exciting to be branching into visuals too now ;-p

Is this still in draft state or would you like reviews already?

**Comment by meike-h** [comment]
Hi!
For now the image is rather simple, but I think it is a good base for new ideas.
I would welcome reviews.

**Comment by AljoschaMeyer** [comment]
@sandreae the module worked for me:

```
$ git clone https://github.com/meike-h/earwig.git
$ cd earwig
$ cargo build
$ ./target/debug/in | ./target/debug/imaginary img.png
```

Yields a black-and-white diagram (bottom half uses the inverted colors of the top half).

**Comment by AljoschaMeyer** [comment]
img

**Comment by sandreae** [comment]
Ah! Now it works for me, I love it, looks great!

This is what I got last time for some reason:
image

**Comment by sandreae** [comment]
> Hi! For now the image is rather simple, but I think it is a good base for new ideas. I would welcome reviews.

Great, I think simple imagery fits the project well :-) merging now!

**Review by sandreae — APPROVED** [review]
Really nice addition, thanks!

**Pull request merged**
